# Generated by Django 3.2.4 on 2021-07-03 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Developer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='developers')),
                ('age', models.IntegerField()),
                ('description', models.TextField()),
                ('email', models.EmailField(max_length=200)),
                ('phone', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': 'Developer',
                'verbose_name_plural': 'Developers',
            },
        ),
        migrations.CreateModel(
            name='Startapper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('video', models.FileField(upload_to='media')),
                ('audio', models.FileField(blank=True, upload_to='media')),
                ('pdf', models.FileField(upload_to='documents/%Y/%m/%d/')),
                ('document', models.FileField(upload_to='documents/%Y/%m/%d/')),
                ('description', models.TextField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Startapper',
                'verbose_name_plural': 'Startappers',
            },
        ),
    ]
